version: "2.1"

services:
  api:
    image: node:12-alpine
    command: >
      sh -c "yarn && yarn typeorm migration:run && yarn dev:server"
    volumes:
      - .:/src
      - ./node_modules:/src/node_modules
    env_file: .env
    working_dir: /src
    ports:
      - "3333:3333"
    depends_on:
      - database

  database:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
